---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  namespace: consul
  labels:
    app: consul
spec:
  selector:
    matchLabels:
      app: consul
  replicas: 1
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: hashicorp/consul:1.9.4
          ports:
            - containerPort: 8500
---
apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  selector:
    app: consul
  ports:
    - name: tcp
      port: 8500
      protocol: TCP
      targetPort: 8500
